<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>FairyPam.Guardian</AssemblyName>
    <RootNamespace>FairyPam.Guardian</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSelfContained>true</PublishSelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../FairyPam.Agent.Core/FairyPam.Agent.Core.csproj" />
  </ItemGroup>
</Project>
