[workspace]
members = [
    "bins/fairypam-agent",
    "bins/fairypam-agent-installer",
    "bins/fairypam-agentctl",
    "bins/fairypam-agent-guardian",
    "crates/fairypam-agent-core",
    "crates/fairypam-agent-dev-automation",
    "crates/fairypam-agent-guardian-protocol",
    "crates/fairypam-agent-input",
    "crates/fairypam-agent-local-client",
    "crates/fairypam-agent-local-protocol",
    "crates/fairypam-agent-protocol",
    "crates/fairypam-agent-transport",
    "crates/fairypam-agent-windows",
]
default-members = [
    "bins/fairypam-agent",
    "bins/fairypam-agentctl",
    "bins/fairypam-agent-guardian",
    "crates/fairypam-agent-core",
    "crates/fairypam-agent-guardian-protocol",
    "crates/fairypam-agent-input",
    "crates/fairypam-agent-local-client",
    "crates/fairypam-agent-local-protocol",
    "crates/fairypam-agent-protocol",
    "crates/fairypam-agent-transport",
    "crates/fairypam-agent-windows",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "2"
zip = { version = "2.4", default-features = false, features = ["deflate"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
ed25519-dalek = "2.2"
