use std::{collections::BTreeSet, time::Instant};

use fairypam_agent_core::state::Effect;
use sha2::{Digest, Sha256};
use thiserror::Error;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AutomationTarget {
    Testbed,
    LiveGame,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum AutomationCapability {
    Capture,
    Input,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DevSession {
    pub nonce: [u8; 32],
    pub audit_id: [u8; 16],
    pub caller_sid_hash: String,
    pub target: AutomationTarget,
    pub capabilities: BTreeSet<AutomationCapability>,
    pub expires_at: Instant,
    pub build_id: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DevSessionRequest {
    pub caller_sid: String,
    pub target: AutomationTarget,
    pub capabilities: BTreeSet<AutomationCapability>,
    pub expires_at: Instant,
    pub build_id: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DevSessionRevocationReason {
    ClientDisconnected,
    Expired,
    EmergencyStop,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DevSessionRevocation {
    pub audit_id: [u8; 16],
    pub reason: DevSessionRevocationReason,
}

#[derive(Clone, Debug, Error, PartialEq, Eq)]
#[error("{code}: {message}")]
pub struct DevSessionError {
    code: &'static str,
    message: String,
}

impl DevSessionError {
    pub const fn code(&self) -> &'static str {
        self.code
    }

    pub fn expired() -> Self {
        Self::new(
            "dev.session.expired",
            "the Dev Automation session expired; reconnect before sending another action",
        )
    }

    fn new(code: &'static str, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
        }
    }
}

#[derive(Default)]
pub struct DevSessionManager {
    active: Option<DevSession>,
    last_revocation: Option<DevSessionRevocation>,
}

impl DevSessionManager {
    pub fn create(
        &mut self,
        caller_sid: &str,
        target: AutomationTarget,
        capabilities: BTreeSet<AutomationCapability>,
        expires_at: Instant,
        build_id: impl Into<String>,
        now: Instant,
    ) -> Result<DevSession, DevSessionError> {
        let mut nonce = [0_u8; 32];
        getrandom::fill(&mut nonce).map_err(|error| {
            DevSessionError::new("dev.session.nonce_unavailable", error.to_string())
        })?;
        self.create_with_nonce(
            nonce,
            DevSessionRequest {
                caller_sid: caller_sid.to_owned(),
                target,
                capabilities,
                expires_at,
                build_id: build_id.into(),
            },
            now,
        )
    }

    /// Creates a session bound to the already-validated local-protocol nonce.
    /// The caller is accepted only after Named Pipe token validation, while the
    /// nonce is generated by the shared local client and protected by its
    /// replay guard before this method is reached.
    pub fn create_with_nonce(
        &mut self,
        nonce: [u8; 32],
        request: DevSessionRequest,
        now: Instant,
    ) -> Result<DevSession, DevSessionError> {
        if self.active.is_some() {
            return Err(DevSessionError::new(
                "dev.session.already_active",
                "revoke the active Dev Automation session before creating another",
            ));
        }
        if request.target != AutomationTarget::Testbed {
            return Err(DevSessionError::new(
                "dev.session.target_denied",
                "unattended Dev Automation is restricted to fairypam-agent-testbed",
            ));
        }
        if request.capabilities.is_empty() || request.expires_at <= now {
            return Err(DevSessionError::new(
                "dev.session.window_invalid",
                "Dev Automation session requires capabilities and a future expiry",
            ));
        }
        let mut audit_id = [0_u8; 16];
        getrandom::fill(&mut audit_id).map_err(|error| {
            DevSessionError::new("dev.session.nonce_unavailable", error.to_string())
        })?;
        let session = DevSession {
            nonce,
            audit_id,
            caller_sid_hash: hash(&request.caller_sid),
            target: request.target,
            capabilities: request.capabilities,
            expires_at: request.expires_at,
            build_id: request.build_id,
        };
        self.active = Some(session.clone());
        Ok(session)
    }

    pub fn expire_active(&mut self, now: Instant) -> Vec<Effect> {
        let Some(nonce) = self.active.as_ref().map(|session| session.nonce) else {
            return Vec::new();
        };
        self.on_expiry(nonce, now)
    }

    pub fn last_revocation(&self) -> Option<&DevSessionRevocation> {
        self.last_revocation.as_ref()
    }

    pub fn active_nonce(&self) -> Option<[u8; 32]> {
        self.active.as_ref().map(|session| session.nonce)
    }

    pub fn active_expires_at(&self) -> Option<Instant> {
        self.active.as_ref().map(|session| session.expires_at)
    }

    pub fn authorize(
        &self,
        nonce: [u8; 32],
        capability: AutomationCapability,
        now: Instant,
    ) -> Result<(), DevSessionError> {
        let Some(session) = &self.active else {
            return Err(DevSessionError::new(
                "dev.session.missing",
                "no active Dev Automation session",
            ));
        };
        if session.nonce != nonce
            || session.expires_at <= now
            || !session.capabilities.contains(&capability)
        {
            return Err(DevSessionError::new(
                "dev.session.capability_denied",
                "session capability is unavailable",
            ));
        }
        Ok(())
    }

    pub fn on_client_disconnect(&mut self, nonce: [u8; 32]) -> Vec<Effect> {
        self.revoke_matching(nonce, DevSessionRevocationReason::ClientDisconnected)
    }

    pub fn on_expiry(&mut self, nonce: [u8; 32], now: Instant) -> Vec<Effect> {
        if self
            .active
            .as_ref()
            .is_some_and(|session| session.nonce == nonce && session.expires_at <= now)
        {
            return self.revoke_matching(nonce, DevSessionRevocationReason::Expired);
        }
        Vec::new()
    }

    pub fn emergency_stop(&mut self) -> Vec<Effect> {
        self.active.take().map_or_else(Vec::new, |session| {
            self.last_revocation = Some(DevSessionRevocation {
                audit_id: session.audit_id,
                reason: DevSessionRevocationReason::EmergencyStop,
            });
            effects_for(session)
        })
    }

    fn revoke_matching(
        &mut self,
        nonce: [u8; 32],
        reason: DevSessionRevocationReason,
    ) -> Vec<Effect> {
        match self.active.take_if(|session| session.nonce == nonce) {
            Some(session) => {
                self.last_revocation = Some(DevSessionRevocation {
                    audit_id: session.audit_id,
                    reason,
                });
                effects_for(session)
            }
            None => Vec::new(),
        }
    }
}

fn effects_for(session: DevSession) -> Vec<Effect> {
    if session.capabilities.contains(&AutomationCapability::Input) {
        vec![Effect::ReleaseAll]
    } else {
        Vec::new()
    }
}

fn hash(value: &str) -> String {
    Sha256::digest(value.as_bytes())
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}
