<Project Sdk="MSTest.Sdk/4.3.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>FairyPam.Agent.Tests</AssemblyName>
    <RootNamespace>FairyPam.Agent.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/FairyPam.Agent.Core/FairyPam.Agent.Core.csproj" />
  </ItemGroup>
</Project>
