[package]
name = "fairypam-agent-protocol"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
prost = "0.14"
serde.workspace = true
sha2.workspace = true
serde_json.workspace = true
tonic = { version = "0.14", default-features = false, features = ["codegen"] }
tonic-prost = "0.14"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
    "Win32_System_Memory",
    "Win32_System_IO",
    "Win32_System_Pipes",
] }

[build-dependencies]
protoc-bin-vendored = "3"
tonic-prost-build = "0.14"
