[package]
name = "fairypam-agent-updater"
version.workspace = true
edition.workspace = true
publish.workspace = true
build = "build.rs"

[dependencies]
fairypam-agent-suite = { path = "../../crates/fairypam-agent-suite" }
serde_json.workspace = true

[[bin]]
name = "fairypam-agent-updater"
path = "src/main.rs"
